In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [2]:
vect= CountVectorizer()


In [3]:
message=["HEY hey Hey lets go grt lunch today",
         "Did you go home?",
         "Hey ! i need a Favor"]

In [4]:
vect.fit(message)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [5]:
for i in vect.get_feature_names():
    print (i)

did
favor
go
grt
hey
home
lets
lunch
need
today
you


In [6]:
dtm=vect.transform(message)

In [7]:
print(dtm.toarray())

[[0 0 1 1 3 0 1 1 0 1 0]
 [1 0 1 0 0 1 0 0 0 0 1]
 [0 1 0 0 1 0 0 0 1 0 0]]


In [8]:
df=pd.DataFrame(dtm.toarray(),columns=vect.get_feature_names())

In [9]:
df

did  favor  go  grt  hey  home  lets  lunch  need  today  you
0    0      0   1    1    3     0     1      1     0      1    0
1    1      0   1    0    0     1     0      0     0      0    1
2    0      1   0    0    1     0     0      0     1      0    0

In [ ]:

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.datasets import fetch_20newsgroups

data=fetch_20newsgroups()
vect= CountVectorizer()

data.target_news
categories=['talk.religion.misc','comp.graphics','sci.space']
train=fetch_20newsgroups(subset='train',categories=categories)
test=fetch_20newsgroups(subset='test',categories=categories)
