In [ ]:
this is the most used python libraries for data science. numpy consists of a powerful data structure called multidimentional arrays.
numpy is a library written for scientific computing & data analysis. it stands for numerical python and also known as array oriented computing.
the most basic object in numpy is the ndarray or simply an array which is an n-dimensional hompgenious array. by homogenious we means that
all the element in a numpy array have to be of the same data type which is commonly numeric(floator int)

In [242]:
 import numpy as mp
a = mp.array((12,23,45,67,89),dtype=mp.int64)
    

In [254]:
b = mp.array([[12,23,45,67,89],[2,3,5,6,7,],[3,4,5,6,7]],dtype=mp.int64)

In [255]:
b


array([[12, 23, 45, 67, 89],
       [ 2,  3,  5,  6,  7],
       [ 3,  4,  5,  6,  7]], dtype=int64)

In [256]:
b[1:,1:]

array([[3, 5, 6, 7],
       [4, 5, 6, 7]], dtype=int64)

In [245]:
a=mp.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [246]:
a.shape

(4, 3)

In [247]:
a.ndim

2

In [133]:
a.dtype.name

'int32'

In [257]:
a.astype(float)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [134]:
a.itemsize

4

In [135]:
 type(a)
    

numpy.ndarray

In [136]:
 b = mp.array([6, 7, 8])
    

In [137]:
b

array([6, 7, 8])

In [138]:
type(b)

numpy.ndarray

In [139]:
import numpy as np
a = np.array([2,3,4])

In [140]:
a

array([2, 3, 4])

In [141]:
 b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [142]:
type(b)

numpy.ndarray

In [143]:
b.dtype


dtype('float64')

In [144]:
 c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [145]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [146]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [147]:
 np.empty( (2,3) )

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [148]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [149]:
 from numpy import pi
np.linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [150]:
x = np.linspace( 0, 2*pi, 100 )
f = np.sin(x)

In [151]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [152]:
c = np.arange(24).reshape(2,3,4) 
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [153]:
c=np.arange(20000).reshape(200,100)
c

array([[    0,     1,     2, ...,    97,    98,    99],
       [  100,   101,   102, ...,   197,   198,   199],
       [  200,   201,   202, ...,   297,   298,   299],
       ...,
       [19700, 19701, 19702, ..., 19797, 19798, 19799],
       [19800, 19801, 19802, ..., 19897, 19898, 19899],
       [19900, 19901, 19902, ..., 19997, 19998, 19999]])

In [154]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
A * B 

array([[2, 0],
       [0, 4]])

In [155]:
A @ B 

array([[5, 4],
       [3, 4]])

In [156]:
 A.dot(B)

array([[5, 4],
       [3, 4]])

In [157]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [158]:
b+=3
b

array([[3.47814296, 3.88056929, 3.59683807],
       [3.40703336, 3.96710828, 3.5864257 ]])

In [159]:
b+=a
b

array([[6.47814296, 6.88056929, 6.59683807],
       [6.40703336, 6.96710828, 6.5864257 ]])

In [160]:
 import numpy as mp
a = mp.arange(12).reshape(6, 2)

In [161]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [162]:
a.max()

11

In [163]:
B = np.array( [[2,5],[3,4]] )
B

array([[2, 5],
       [3, 4]])

In [164]:
B.max()

5

In [165]:
B.min()

2

In [166]:
x=B.min()

In [167]:
x

2

In [168]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [169]:
 b.sum(axis=0)

array([12, 15, 18, 21])

In [170]:
b.sum(axis=1)

array([ 6, 22, 38])

In [171]:
b.min(axis=0)

array([0, 1, 2, 3])

In [172]:
b.max(axis=0)

array([ 8,  9, 10, 11])

In [173]:
 b.cumsum(axis=1) 

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [174]:
 b.cumsum(axis=0) 

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [175]:
b=np.array([[3,4,6],[5,6,7]])
b

array([[3, 4, 6],
       [5, 6, 7]])

In [176]:
np.sqrt(b)

array([[1.73205081, 2.        , 2.44948974],
       [2.23606798, 2.44948974, 2.64575131]])

In [177]:
c=np.array([[3,4,6],[8,9,1]])
c

array([[3, 4, 6],
       [8, 9, 1]])

In [178]:
np.add(b,c)

array([[ 6,  8, 12],
       [13, 15,  8]])

In [179]:
np.add(b,c)

array([[ 6,  8, 12],
       [13, 15,  8]])

In [180]:
a = np.arange(10)
a 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
a = np.arange(10)*3
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [182]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [183]:
a[2:6]

array([  8,  27,  64, 125], dtype=int32)

In [184]:
a[:2:6]=1200

In [185]:
a

array([1200,    1,    8,   27,   64,  125,  216,  343,  512,  729],
      dtype=int32)

In [186]:
a[:6:2]=1200
a

array([1200,    1, 1200,   27, 1200,  125,  216,  343,  512,  729],
      dtype=int32)

In [187]:
a[:3:2]=1200
a

array([1200,    1, 1200,   27, 1200,  125,  216,  343,  512,  729],
      dtype=int32)

In [188]:
a[:2:2]=1200
a

array([1200,    1, 1200,   27, 1200,  125,  216,  343,  512,  729],
      dtype=int32)

In [189]:
a[:1:2]=1200
a

array([1200,    1, 1200,   27, 1200,  125,  216,  343,  512,  729],
      dtype=int32)

In [190]:
a[:4:3]=1200
a

array([1200,    1, 1200, 1200, 1200,  125,  216,  343,  512,  729],
      dtype=int32)

In [191]:
a[:4:3]=1200
a

array([1200,    1, 1200, 1200, 1200,  125,  216,  343,  512,  729],
      dtype=int32)

In [192]:
a = np.array([5,6,7])
for i in a:
        print(i*(2))

10
12
14


In [193]:
def f(x,y):
        return x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [194]:
def f(x,y):
        return x+y
b = np.fromfunction(f,[3,4],dtype=int)
b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [195]:
b[2,3]
b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [196]:
b[ : ,1]  

array([1, 2, 3])

In [197]:
b[ : ,3]  

array([3, 4, 5])

In [198]:
b[-1]

array([2, 3, 4, 5])

In [199]:
b[::-1]

array([[2, 3, 4, 5],
       [1, 2, 3, 4],
       [0, 1, 2, 3]])

In [200]:
 b[1:3, : ]

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [201]:
 b[0:2, : ]

array([[0, 1, 2, 3],
       [1, 2, 3, 4]])

In [202]:
b[-1] 

array([2, 3, 4, 5])

In [203]:
b[-1::-1] 

array([[2, 3, 4, 5],
       [1, 2, 3, 4],
       [0, 1, 2, 3]])

In [204]:
b[-1::-1] 

array([[2, 3, 4, 5],
       [1, 2, 3, 4],
       [0, 1, 2, 3]])

In [205]:
c = np.array( [[[  0,  1,  2],
[ 10, 12, 13]],
[[100,101,102],
[110,112,113]]])

In [206]:
c.shape

(2, 2, 3)

In [207]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [208]:
for row in b:
    print(row)

[0 1 2 3]
[1 2 3 4]
[2 3 4 5]


In [209]:
for element in b.flat:
    print(element)

0
1
2
3
1
2
3
4
2
3
4
5


In [210]:
 b.ravel()

array([0, 1, 2, 3, 1, 2, 3, 4, 2, 3, 4, 5])

In [211]:
b = np.floor(10*np.random.random((2,2)))
b

array([[4., 9.],
       [7., 3.]])

In [212]:
a = np.floor(10*np.random.random((2,12)))
a

array([[6., 9., 4., 6., 2., 0., 6., 9., 9., 6., 8., 8.],
       [2., 9., 3., 9., 0., 8., 1., 2., 1., 4., 9., 2.]])

In [213]:
np.hsplit(a,3)

[array([[6., 9., 4., 6.],
        [2., 9., 3., 9.]]), array([[2., 0., 6., 9.],
        [0., 8., 1., 2.]]), array([[9., 6., 8., 8.],
        [1., 4., 9., 2.]])]

In [214]:
np.hsplit(a,(3,4))

[array([[6., 9., 4.],
        [2., 9., 3.]]), array([[6.],
        [9.]]), array([[2., 0., 6., 9., 9., 6., 8., 8.],
        [0., 8., 1., 2., 1., 4., 9., 2.]])]

In [215]:
a = np.arange(12)
b = a        
b is a

True

In [216]:
 b.shape = 3,4

In [217]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [218]:
 def f(x):
        print(id(x))

In [219]:
id(a)

2462853511488

In [220]:
f(a)

2462853511488


In [221]:
d = a.copy()              
d is a

False

In [222]:
palette = np.array( [ [0,0,0],[255,0,0],[0,255,0],[0,0,255],[255,255,255] ] )
image = np.array( [ [ 2, 4 ],[ 2,3 ]  ] )

In [223]:
palette[image]

array([[[  0, 255,   0],
        [255, 255, 255]],

       [[  0, 255,   0],
        [  0,   0, 255]]])

In [224]:
 import numpy as np
a = np.array( [ [0,0,0],[255,0,0],[0,255,0],[0,0,255],[255,255,255] ] )
a

array([[  0,   0,   0],
       [255,   0,   0],
       [  0, 255,   0],
       [  0,   0, 255],
       [255, 255, 255]])

In [225]:
a = np.array( [ [0,0,0],[255,0,0],[0,255,0],[0,0,255],[255,255,255] ] )
a.T

array([[  0, 255,   0,   0, 255],
       [  0,   0, 255,   0, 255],
       [  0,   0,   0, 255, 255]])

In [226]:
a = np.arange(12).reshape(3,4)
i = np.array( [ [0,1],[1,2] ] )
j = np.array( [ [0,1],[2,1] ] )
a[i,j]

array([[0, 5],
       [6, 9]])

In [227]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [228]:
a = np.arange(12).reshape(3,4)
i = np.array( [ [1,2],[0,1] ] )
a[i,1]

array([[5, 9],
       [1, 5]])

In [229]:
a[:,j] 

array([[[ 0,  1],
        [ 2,  1]],

       [[ 4,  5],
        [ 6,  5]],

       [[ 8,  9],
        [10,  9]]])

In [230]:
a = np.arange(12).reshape(3,4)
b = a > 4


In [231]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [270]:
a[a>4]

array([ 5,  6,  7,  8,  9, 10, 11])

In [233]:
 a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [234]:
a[b] = 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [265]:
np.random.seed(1)
np.random.randint(0,10,(2,2))

array([[5, 8],
       [9, 5]])

In [266]:
np.random.random((3,3))

array([[0.14675589, 0.09233859, 0.18626021],
       [0.34556073, 0.39676747, 0.53881673],
       [0.41919451, 0.6852195 , 0.20445225]])

In [267]:
q=np.linspace(0,1,5)

In [268]:
q

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [2]:
import numpy as mp
a = mp.array([[12,23,45,67,89],[2,3,5,6,7,],[3,4,5,6,7]],dtype=mp.int64)
a


array([[12, 23, 45, 67, 89],
       [ 2,  3,  5,  6,  7],
       [ 3,  4,  5,  6,  7]], dtype=int64)

In [6]:
a.reshape(3,-1)

array([[12, 23, 45, 67, 89],
       [ 2,  3,  5,  6,  7],
       [ 3,  4,  5,  6,  7]], dtype=int64)

In [10]:
import numpy as np
c=np.arange(10).reshape(5,2)
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
c.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
np.where(c>3)

(array([2, 2, 3, 3, 4, 4], dtype=int64),
 array([0, 1, 0, 1, 0, 1], dtype=int64))

In [16]:
a=np.array([[2,3,4,5],[12,13,14,15],[21,22,23,24]])
a

array([[ 2,  3,  4,  5],
       [12, 13, 14, 15],
       [21, 22, 23, 24]])

In [18]:
np.array(a>12)

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [19]:
np.where(a>12)

(array([1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [23]:
x=np.array([3,4,5,6,7])
y=np.array([4,5,6,7,8])


In [22]:
np.where(x==y)

(array([], dtype=int64),)

In [25]:
a[(a>2)|(a<5)]

array([ 2,  3,  4,  5, 12, 13, 14, 15, 21, 22, 23, 24])

In [51]:
a=np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [52]:
b=a

In [53]:
b[0]=11
b

array([[11, 11],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])

In [54]:
a

array([[11, 11],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])

In [55]:
np.may_share_memory(a,b)

True

In [56]:
a=np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [57]:
b=a.copy()

In [58]:
b[0]=11
b

array([[11, 11],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])

In [59]:
np.may_share_memory(a,b)

False

In [65]:
a=np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [68]:
b=np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
np.dot(a,b)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [79]:
a==b


array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [80]:
b[a==b]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [77]:
b=np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
np.concatenate((a,b),axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [86]:
np.exp(22/7)

23.16997229826248

In [87]:
np.sum(a)

45

In [88]:
np.median(a)

4.5

In [89]:
np.mean(a)

4.5

In [91]:
a.std()

2.8722813232690143

In [92]:
np.logical_or(a,b)

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [93]:
np.logical_and(a,b)

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [94]:
np.all(a==b)

True

In [95]:
a.max()

9

In [100]:
np.random.randint(0,9,(2,2))

array([[0, 2],
       [5, 3]])

In [104]:
np.random.seed(1)
np.random.randint(0,9,(2,2))

array([[5, 8],
       [5, 0]])

In [108]:
np.random.random(6)

array([0.02738759, 0.67046751, 0.4173048 , 0.55868983, 0.14038694,
       0.19810149])

In [109]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [110]:
np.eye(3,k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [112]:
np.eye(3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])