In [157]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

In [158]:
data=fetch_california_housing()

In [159]:
x=data.data
y=data.target

In [160]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=20)

In [161]:
dtr=DecisionTreeClassifier(max_depth=7)

In [183]:
dtr.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=7,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [182]:
dtr.score(x_train,y_train)

1.0

In [181]:
dtr.score(x_test,y_test)

0.9722222222222222

In [165]:
rfc=RandomForestRegressor(n_estimators=20)

In [166]:
rfc.fit(x_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [167]:
rfc.score(x_train,y_train)

0.9663329871200038

In [168]:
rfc.score(x_test,y_test)

0.8088664275401696

# Wine

In [169]:
from sklearn.datasets import load_wine

In [170]:
data=load_wine()

In [171]:
x=data.data
y=data.target

In [172]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=20)

In [173]:
dtr.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=7,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [174]:
dtr.score(x_train,y_train)

1.0

In [175]:
dtr.score(x_test,y_test)

0.9722222222222222

In [176]:
rfr=RandomForestRegressor(n_estimators=50)

In [177]:
rfr.fit(x_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [178]:
rfr.score(x_train,y_train)

0.9863544369151339

In [180]:
rfr.score(x_test,y_test)

0.966118887262079

# house Price Prediction

In [1]:
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

In [2]:
df=pd.read_csv('E:/python/house-prices-advanced-regression-techniques/train.csv')

In [3]:
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
0         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
1         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
2         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
3         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
4         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  
3      2   2006        WD        Abnorml     140000  
4     12   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [4]:
numeric_variables=['Id','MSSubClass','LotFrontage','LotArea','SalePrice','MoSold','YrSold']

df[numeric_variables].head()

Id  MSSubClass  LotFrontage  LotArea  SalePrice  MoSold  YrSold
0   1          60         65.0     8450     208500       2    2008
1   2          20         80.0     9600     181500       5    2007
2   3          60         68.0    11250     223500       9    2008
3   4          70         60.0     9550     140000       2    2006
4   5          60         84.0    14260     250000      12    2008

In [5]:
df['LotFrontage'].isnull().sum()

259

In [6]:
df['LotFrontage']=df['LotFrontage'].fillna(df['LotFrontage']).median()
df['LotFrontage'].isnull().sum()

0

In [7]:
x = df.iloc[:,4].values.reshape(-1,1)
x.shape

(1460, 1)

In [8]:
x

array([[ 8450],
       [ 9600],
       [11250],
       ...,
       [ 9042],
       [ 9717],
       [ 9937]], dtype=int64)

In [9]:
y = df.iloc[:,80].values.reshape(-1,1)

In [10]:
y

array([[208500],
       [181500],
       [223500],
       ...,
       [266500],
       [142125],
       [147500]], dtype=int64)

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=20)

In [12]:
rf=RandomForestRegressor(n_estimators=50)

In [13]:
rf.fit(x_train,y_train)

C:\Users\PADAM\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [14]:
rf.score(x_train,y_train)

0.8016731940680233

In [15]:
rf.fit(x_test,y_test)

C:\Users\PADAM\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [16]:
rf.score(x_test,y_test)

0.8016063985736516

In [30]:
gh=pd.read_csv('E:/python/house-prices-advanced-regression-techniques/test.csv')

In [31]:
gh.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities      ...       ScreenPorch PoolArea PoolQC  Fence  \
0         Lvl    AllPub      ...               120        0    NaN  MnPrv   
1         Lvl    AllPub      ...                 0        0    NaN    NaN   
2         Lvl    AllPub      ...                 0        0    NaN  MnPrv   
3         Lvl    AllPub      ...                 0        0    NaN    NaN   
4         HLS    AllPub      ...               144        0    NaN    NaN   

  MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0         NaN       0      6    2010        WD         Normal  
1        Gar2   12500      6    2010        WD         Normal  
2         NaN       0      3    2010        WD         Normal  
3         NaN       0      6    2010        WD         Normal  
4         NaN       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [32]:
num_var=['Id','MSSubClass','LotFrontage','LotArea']

gh[num_var].head()

Id  MSSubClass  LotFrontage  LotArea
0  1461          20         80.0    11622
1  1462          20         81.0    14267
2  1463          60         74.0    13830
3  1464          60         78.0     9978
4  1465         120         43.0     5005

In [33]:
gh['LotFrontage'].isnull().sum()

227

In [186]:
#df.fillna({'LotFrontage':df.LotFrontage.mean()}).head()

In [34]:
gh['LotFrontage']=gh['LotFrontage'].fillna(gh['LotFrontage']).median()
gh['LotFrontage'].isnull().sum()

0

In [35]:
x2 = gh.iloc[:,1].values.reshape(-1,1)
x2.shape

(1459, 1)

In [36]:
x2

array([[20],
       [20],
       [60],
       ...,
       [20],
       [85],
       [60]], dtype=int64)

In [37]:
y2= gh.iloc[:,4].values
y2.shape

(1459,)

In [38]:
y2

array([11622, 14267, 13830, ..., 20000, 10441,  9627], dtype=int64)

In [39]:
rf.fit(x_test,y_test)

C:\Users\PADAM\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [40]:
rf.score(x_test,y_test)

0.822571854302916

In [41]:
rf.fit(x_train,y_train)

C:\Users\PADAM\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [42]:
rf.score(x_train,y_train)

0.7997112550015267

# classifier

In [86]:
dtr=RandomForestClassifier(max_depth=30)

In [87]:
dtr.fit(x_train,y_train)

C:\Users\PADAM\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\PADAM\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=30, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [88]:
dtr.score(x_train,y_train)

0.711472602739726

In [89]:
dtr.fit(x_test,y_test)

C:\Users\PADAM\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=30, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [90]:
dtr.score(x_test,y_test)

0.8493150684931506